### PR TITLE
bump react version in package.json to support react v15

### PR DESCRIPTION
**Pull request by divyenduz**
Bumped the react version in package.json to support react v15

For the time being I am maintaining :-
https://github.com/divyenduz/react-google-publisher-tag

As soon as this repository starts supporting react v15. I will delete mine.

Thanks

### CODE REVIEW

**Comment by seeden** [comment]
thanks

**Comment by divyenduz** [comment]
Are you planning to publish this merge to npm anytime soon ? 

Cheers,

**Comment by seeden** [comment]
It is published as 0.1.16 with targeting support as well

**Comment by divyenduz** [comment]
Thanks

**Pull request merged**
